# Generated by Django 4.2.16 on 2026-02-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='Step 7', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='climate',
            field=models.CharField(blank=True, help_text='Step 5', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='concerns',
            field=models.TextField(blank=True, help_text='Step 3', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ingredient_preferences',
            field=models.TextField(blank=True, help_text='Step 6', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_allergies',
            field=models.TextField(blank=True, help_text='Step 7 custom', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sensitivity_level',
            field=models.CharField(blank=True, help_text='Step 4', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skin_type',
            field=models.CharField(help_text='Step 2', max_length=100),
        ),
    ]
