# Generated by Django 4.2.16 on 2026-02-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_allergies_userprofile_climate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='SkinAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='analyses/')),
                ('hydration_level', models.IntegerField(help_text='Percentage 0-100')),
                ('sun_damage', models.CharField(max_length=100)),
                ('acne_status', models.CharField(max_length=100)),
                ('fine_lines', models.CharField(max_length=100)),
                ('overall_score', models.IntegerField()),
                ('recommendation_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.user')),
            ],
        ),
    ]
